---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: monitoring
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
          label1: value1
      logging:

    processors:
      batch:

    extensions:
      health_check:
      pprof:
        endpoint: :1888
      zpages:
        endpoint: :55679

    service:
      extensions: [pprof, zpages, health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, prometheus]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      nodeName: h00525479-dev-02
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.37.1
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - mountPath: /var/log
              name: varlog
              readOnly: true
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /etc/otel/config.yaml
              name: data
              subPath: config.yaml
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: data
          configMap:
            name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  type: NodePort
  ports:
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
      protocol: TCP
      targetPort: 8888
      nodePort: 31522
    - name: metrics1
      port: 8889
      protocol: TCP
      targetPort: 8889
      nodePort: 31961
    - name: otel-endpoint
      port: 4317
      protocol: TCP
      targetPort: 4317
      nodePort: 31963
  selector:
    component: otel-collector
