apiVersion: v1
kind: Service
metadata:
  name: demo-server
  namespace: monitoring
spec:
  selector:
    app: demo-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 7080
      targetPort: 7080
      nodePort: 31121
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-server
  name: demo-server
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: demo-server
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      #     use label to selector node
      nodeName: h00525479-dev-0003
      containers:
        - name: demo-server
          env: 
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: 119.8.58.38:31963
          image: kevindavis/demo-server:0.02
          ports:
            - containerPort: 7080
              protocol: TCP
