apiVersion: v1
kind: Pod
metadata:
  generateName: node-exporter-
  labels:
    app: node-exporter
  name: node-exporter-zmqbw1
  namespace: monitoring
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: node-exporter
    uid: 1d1fd1e6-ff7f-40d9-8894-fe8ffc9cc86f
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - edge-03
  containers:
  - image: prom/node-exporter:v0.16.0
    imagePullPolicy: IfNotPresent
    name: node-exporter
    ports:
    - containerPort: 9100
      hostPort: 9100
      name: http
      protocol: TCP
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
