apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-client
  name: demo-client
  namespace: monitoring
spec:
  selector:
    matchLabels:
      monitor: demo-client
  template:
    metadata:
      labels:
        monitor: demo-client
    spec:
      #     use label to selector node
      nodeName: h00525479-dev-0003
      containers:
      - name: demo-client
        image: kevindavis/demo-client:0.01